carrito/urls.py
from django.urls import path
from . import views

app_name = 'carrito'

urlpatterns = [
    path('', views.carrito_resumen, name='carrito_resumen'),
    path('agregar/', views.carrito_agregar, name='carrito_agregar'),
    path('eliminar/', views.carrito_eliminar, name='carrito_eliminar'),
    path('actualizar/', views.carrito_actualizar, name='carrito_actualizar'),
]

cuenta/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .forms import (UsuarioLoginForm, PasswordReiniciarForm, PasswordReiniciarConfirmacionForm)
from . import views

app_name = 'cuenta'

urlpatterns = [
  path('login/', auth_views.LoginView.as_view(
    template_name='cuenta/registro/login.html', 
    form_class=UsuarioLoginForm), 
    name='login'),

  path('logout/', auth_views.LogoutView.as_view(
    next_page='/cuenta/login/'), 
    name='logout'),

  path('registrar/', views.registrar_cuenta, name='registrar'),

  path('activar/<slug:uidb64>/<slug:token>', views.activar_cuenta, name='activar'),

  path('reiniciar_password/', auth_views.PasswordResetView.as_view (
    template_name='cuenta/usuario/reiniciar_password.html', 
    success_url='reiniciar_password_confirmacion_email', #1
    email_template_name='cuenta/usuario/reiniciar_password_email.html',
    form_class=PasswordReiniciarForm),
    name='reiniciar_password'),
  #1
  path('reiniciar_password/reiniciar_password_confirmacion_email/', TemplateView.as_view(
    template_name="cuenta/usuario/reiniciar_estado.html"), 
    name='reiniciar_password_hecho'),

  path('reiniciar_password_confirmacion/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
  template_name='cuenta/usuario/reiniciar_password_confirmacion.html', 
  success_url='/cuenta/reiniciar_password_completo/', #2
  form_class=PasswordReiniciarConfirmacionForm),
  name="reiniciar_password_confirmacion"),
  #2
  path('reiniciar_password_completo/', TemplateView.as_view(template_name="cuenta/usuario/reiniciar_estado.html"), name='reiniciar_password_completo'),

  # Panel de control del usuario
  path('control_panel/', views.control_panel, name='control_panel'),

  path('perfil/editar/', views.editar_detalles, name='editar_detalles'),

  path('perfil/eliminar/', views.eliminar_usuario, name='eliminar_usuario'),

  path('perfil/eliminar_confirmacion/', TemplateView.as_view(
    template_name='cuenta/usuario/eliminar_confirmacion.html'), 
    name='eliminar_confirmacion'),
]

nucleo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls', namespace='tienda')),
    path('carrito/', include('carrito.urls', namespace='carrito')),
    path('cuenta/', include('cuenta.urls', namespace='cuenta')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carrito/models.py
from django.db import models

# Create your models here.

carrito/views.py
from django.shortcuts import render, get_object_or_404
from .carrito import Carrito
from tienda.models import Producto
from django.http import JsonResponse

def carrito_resumen(request):
  carrito = Carrito(request)
  return render(request, 'carrito/resumen.html', {'carrito':carrito})

def carrito_agregar(request):
  carrito = Carrito(request)
  if request.POST.get('action') == 'post':
    producto_id = int(request.POST.get('productoid'))
    producto_cantidad = int(request.POST.get('productocantidad'))
    producto = get_object_or_404(Producto, id=producto_id)
    carrito.agregar(producto=producto, cantidad=producto_cantidad)

    carrito_cantidad = carrito.__len__()
    respuesta = JsonResponse({'cantidad':carrito_cantidad})
    return respuesta

def carrito_eliminar(request):
  carrito = Carrito(request)
  if request.POST.get('action') == 'post':
    producto_id = int(request.POST.get('productoid'))
    carrito.eliminar(producto=producto_id)

    carrito_cantidad = carrito.__len__()
    carrito_total = carrito.get_precio_total()
    
    respuesta = JsonResponse({'cantidad':carrito_cantidad, 'subtotal':carrito_total})
    return respuesta

def carrito_actualizar(request):
  carrito = Carrito(request)
  if request.POST.get('action') == 'post':
    producto_id = int(request.POST.get('productoid'))
    producto_cantidad = int(request.POST.get('productocantidad'))
    carrito.actualizar(producto=producto_id, cantidad=producto_cantidad)

    carrito_cantidad = carrito.__len__()
    carrito_total = carrito.get_precio_total()
    
    respuesta = JsonResponse({'cantidad':carrito_cantidad, 'subtotal':carrito_total})
    return respuesta

templates/carrito/resumen.html
{% extends '../tienda/base.html' %}
{% load static %}

{% block titulo %} Carrito Resumen {% endblock %}

{% block contenido %}

<main class="pt-5">
  <div class="container">
    <h1 class="h5">Carrito de compras</h1>
    {% for item in carrito %}
      {% with producto=item.producto %}
      <div data-index="{{ producto.id }}" class="row mb-4 border product-item">
        <div class="col-md-3 col-lg-2 order-md-first bg-light">
          <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ producto.imagen.url }}">
        </div>
        <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
          <a href="{{ producto.get_absolute_url }}" class="text-decoration-none text-reset">
            <h1 class="h5 pt-2">{{ producto.titulo }}</h1>
          </a>
          <div class="border">
            <div class="col border-bottom">
              <div class="row p-3">
                <div class="col-6">Hardback Book</div>
                <div class="col-6 text-end">
                  <span class="h6 fw-bold">${{ item.precio_total }}</span>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="row p-3">
                <div class="col-12">
                  <label for="select">Cantidad</label>
                  <select id="select{{ producto.id }}">
                    <option selected>
                      {{ item.cantidad }}
                    </option>
                    <option value="">1</option>
                    <option value="">2</option>
                    <option value="">3</option>
                    <option value="">4</option>
                  </select>
                  <button type="button" id="update-button" data-index="{{ producto.id }}"
                    class="btn btn-outline-secondary btn-sm update-button">
                    Actualizar
                  </button>
                  <button type="button" id="delete-button" data-index="{{ producto.id }}"
                    class="btn btn-outline-secondary btn-sm delete-button">
                    Eliminar
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endwith %}
    {% endfor %}
    <div class="col-12 text-end">
      <div class="h6 fw-bold">Sub Total: $
        <div id="subtotal" class="d-inline-flex">{{carrito.get_precio_total}}</div>
      </div>
    </div>
  </div>
</main>

<script>
  // Eliminar producto del carrito
  $(document).on('click', '#delete-button', function (e) {
    e.preventDefault();
    var producto_id = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "carrito:carrito_eliminar" %}',
      data: {
        productoid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function(json){
        $('.product-item[data-index="'+ producto_id +'"]').remove();
        document.getElementById("carrito-cantidad").innerHTML = json.cantidad
        // "carrito-cantidad" esta en base.html
        document.getElementById("subtotal").innerHTML = json.subtotal
      },
      error: function(xhr, errmsd, err) {

      }
    });
  })
</script>

<script>
  // Actualizar producto del carrito
  $(document).on('click', '#update-button', function (e) {
    e.preventDefault();
    var producto_id = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "carrito:carrito_actualizar" %}',
      data: {
        productoid: $(this).data('index'),
        productocantidad: $('#select' + producto_id + ' option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function(json){
        document.getElementById("carrito-cantidad").innerHTML = json.cantidad
        // "carrito-cantidad" esta en base.html
        document.getElementById("subtotal").innerHTML = json.subtotal
      },
      error: function(xhr, errmsd, err) {

      }
    });
  })
</script>

{% endblock %}