cuenta/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .forms import (UsuarioLoginForm, PasswordReiniciarForm, PasswordReiniciarConfirmacionForm)
from . import views

app_name = 'cuenta'

urlpatterns = [
  path('login/', auth_views.LoginView.as_view(
    template_name='cuenta/registro/login.html', 
    form_class=UsuarioLoginForm), 
    name='login'),

  path('logout/', auth_views.LogoutView.as_view(
    next_page='/cuenta/login/'), 
    name='logout'),

  path('registrar/', views.registrar_cuenta, name='registrar'),

  path('activar/<slug:uidb64>/<slug:token>', views.activar_cuenta, name='activar'),

  path('reiniciar_password/', auth_views.PasswordResetView.as_view (
    template_name='cuenta/usuario/reiniciar_password.html', 
    success_url='reiniciar_password_confirmacion_email', #1
    email_template_name='cuenta/usuario/reiniciar_password_email.html',
    form_class=PasswordReiniciarForm),
    name='reiniciar_password'),
  #1
  path('reiniciar_password/reiniciar_password_confirmacion_email/', TemplateView.as_view(
    template_name="cuenta/usuario/reiniciar_estado.html"), 
    name='reiniciar_password_hecho'),

  path('reiniciar_password_confirmacion/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
  template_name='cuenta/usuario/reiniciar_password_confirmacion.html', 
  success_url='/cuenta/reiniciar_password_completo/', #2
  form_class=PasswordReiniciarConfirmacionForm),
  name="reiniciar_password_confirmacion"),
  #2
  path('reiniciar_password_completo/', TemplateView.as_view(template_name="cuenta/usuario/reiniciar_estado.html"), name='reiniciar_password_completo'),

  # Panel de control del usuario
  path('control_panel/', views.control_panel, name='control_panel'),

  path('perfil/editar/', views.editar_detalles, name='editar_detalles'),

  path('perfil/eliminar/', views.eliminar_usuario, name='eliminar_usuario'),

  path('perfil/eliminar_confirmacion/', TemplateView.as_view(
    template_name='cuenta/usuario/eliminar_confirmacion.html'), 
    name='eliminar_confirmacion'),
]

nucleo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls', namespace='tienda')),
    path('carrito/', include('carrito.urls', namespace='carrito')),
    path('cuenta/', include('cuenta.urls', namespace='cuenta')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cuenta/models.py
from django.db import models
from django_countries.fields import CountryField
from django.utils.translation import gettext_lazy
from django.core.mail import send_mail

from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager, PermissionsMixin)

class AdministradorCuentas(BaseUserManager):
  def create_superuser(self, email, nombre_usuario, password, **other_fields):

    other_fields.setdefault('is_staff', True)
    other_fields.setdefault('is_superuser', True)
    other_fields.setdefault('is_active', True)

    if other_fields.get('is_staff') is not True:
      raise ValueError('El superusuario debe estar asignado a is_staff=True.')
      
    if other_fields.get('is_superuser') is not True:
      raise ValueError('El superusuario debe estar asignado a is_superuser=True.')

    return self.create_user(email, nombre_usuario, password, **other_fields)

  def create_user(self, email, nombre_usuario, password, **other_fields):
      if not email:
        raise ValueError(gettext_lazy('Debes proporcionar una dirección de correo electrónico'))

      email = self.normalize_email(email)
      usuario = self.model(email=email,  nombre_usuario=nombre_usuario,**other_fields)
      usuario.set_password(password)
      usuario.save()
      return usuario

class UsuarioBase(AbstractBaseUser, PermissionsMixin):
  email = models.EmailField(gettext_lazy('direccion email'), unique=True)
  nombre_usuario = models.CharField(max_length=150, unique=True)
  nombre = models.CharField(max_length=150, blank=True)
  apellido = models.CharField(max_length=150, blank=True)
  pais = CountryField()
  provincia = models.CharField(max_length=150, blank=True)
  numero_telefono = models.CharField(max_length=15, blank=True)
  codigo_postal = models.CharField(max_length=12, blank=True)
  direccion = models.CharField(max_length=150, blank=True)
  nota = models.TextField(gettext_lazy('acerca_de'), max_length=500, blank=True)

  # is_active respetar el nombre en ingles
  is_active = models.BooleanField(default=False)
  is_staff = models.BooleanField(default=False)
  creado = models.DateTimeField(auto_now_add=True)
  actualizado = models.DateTimeField(auto_now=True)

  objetos = AdministradorCuentas()

  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = ['nombre_usuario']
  
  def email_usuario(self, asunto, mensaje):
    send_mail(
        asunto,
        mensaje,
        'l@1.com',
        [self.email],
        fail_silently=False,
    )

  class Meta:
    verbose_name = 'Cuentas'
    verbose_name_plural = 'Cuentas'

  def __str__(self):
    return self.nombre_usuario

cuenta/forms.py
from django import forms
from .models import UsuarioBase
from django.contrib.auth.forms import (AuthenticationForm, PasswordResetForm, SetPasswordForm)


class UsuarioLoginForm(AuthenticationForm):
  # username respetar el nombre en ingles
  username = forms.CharField(label='E-mail',widget=forms.TextInput(
      attrs={'class': 'form-control mb-3', 'placeholder': 'E-mail', 'id': 'login-username'}))
  password = forms.CharField(label='Contraseña',widget=forms.PasswordInput(
      attrs={'class': 'form-control', 'placeholder': 'Contraseña', 'id': 'login-pwd'}
  ))


class RegistroForm(forms.ModelForm):
  
  nombre_usuario = forms.CharField(label='Nombre de Usuario', max_length=50, min_length=4, help_text='Requerido')
  email = forms.EmailField(max_length=100, help_text='Requerido', error_messages={'requerido': 'Necesitas un email'})
  password = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
  password2 = forms.CharField(label='Repetir Contraseña', widget=forms.PasswordInput)

  class Meta:
    model = UsuarioBase
    fields = ('nombre_usuario', 'email')

  def clean_user_name(self):
    nombre_usuario = self.cleaned_data['nombre_usuario'].lower()
    r = UsuarioBase.objects.filter(nombre_usuario=nombre_usuario)
    if r.count():
      print('raise hijo de puta')
      raise forms.ValidationError("El nombre de usuario ya existe")
    return nombre_usuario

  def limpiar_password(self):
    cd = self.cleaned_data
    if cd['password'] != cd['password2']:
      raise forms.ValidationError("Las contraseñas no coinciden")
    return cd['password2']

  def limpiar_email(self):
    email = self.cleaned_data['email']
    x = UsuarioBase.objects.filter(email=email)
    if x.exists():
      raise forms.ValidationError('El email ya esta en uso')
    return email

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['nombre_usuario'].widget.attrs.update(
      {'class': 'form-control mb-3', 'placeholder': 'Nombre de usuario'}
    )
    self.fields['email'].widget.attrs.update(
      {'class': 'form-control mb-3', 'placeholder': 'E-mail', 'name': 'email', 'id': 'id_email'}
    )
    self.fields['password'].widget.attrs.update(
      {'class': 'form-control mb-3', 'placeholder': 'Contraseña'}
    )
    self.fields['password2'].widget.attrs.update(
      {'class': 'form-control', 'placeholder': 'Repetir Contraseña'}
    )


class EditarUsuarioForm(forms.ModelForm):

  email = forms.EmailField(label='E-mail (no se puede cambiar)', max_length=200, 
    widget=forms.TextInput(
      attrs={'class': 'form-control mb-3', 'placeholder': 'E-mail', 'id': 'form-email', 'readonly': 'readonly'}))

  nombre_usuario = forms.CharField(label='Nombre de Usuario', min_length=4, max_length=50,
    widget=forms.TextInput(
      attrs={'class': 'form-control mb-3', 'placeholder': 'Nombre de Usuario', 'id': 'form-firstname', 'readonly': 'readonly'}))

  nombre = forms.CharField(label='Nombre', min_length=4, max_length=50, 
    widget=forms.TextInput(
      attrs={'class': 'form-control mb-3', 'placeholder': 'Nombre', 'id': 'form-lastname'}))

  class Meta:
    model = UsuarioBase
    fields = ('email', 'nombre_usuario', 'nombre',)

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['nombre_usuario'].required = True
    self.fields['email'].required = True


class PasswordReiniciarForm(PasswordResetForm):

  email = forms.EmailField(max_length=254, label='E-mail',
    widget=forms.TextInput(
      attrs={'class': 'form-control mb-3', 'placeholder': 'E-mail', 'id': 'form-email'}))

  def limpiar_email(self):
    email = self.cleaned_data['email']
    u = UsuarioBase.objetos.filter(email=email)
    if not u:
      raise forms.ValidationError(
        'Desafortunadamente no se ha podido encontrar el E-mail')
    return email


class PasswordReiniciarConfirmacionForm(SetPasswordForm):
  # new_password1 y new_password2 respetar el nombre en ingles
  new_password1 = forms.CharField(label='Nueva Contraseña', 
  widget=forms.PasswordInput(
    attrs={'class': 'form-control mb-3', 'placeholder': 'Nueva Contraseña', 'id': 'form-newpass'}))

  new_password2 = forms.CharField(label='Repetir Contraseña', 
  widget=forms.PasswordInput(
    attrs={'class': 'form-control mb-3', 'placeholder': 'Repetir Contraseña', 'id': 'form-new-pass2'}))

cuenta/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from .forms import RegistroForm, EditarUsuarioForm
from .tokens import activar_token_cuenta
from .models import UsuarioBase


@login_required
def control_panel(request):
  return render(request, 'cuenta/usuario/control_panel.html')


@login_required
def editar_detalles(request):
  if request.method == 'POST':
    usuario_form = EditarUsuarioForm(instance=request.user, data=request.POST)

    if usuario_form.is_valid():
      usuario_form.save()

  else:
    usuario_form = EditarUsuarioForm(instance=request.user)

  return render(request,'cuenta/usuario/editar_detalles.html', {'usuario_form': usuario_form})


@login_required
def eliminar_usuario(request):
  usuario = UsuarioBase.objetos.get(nombre_usuario=request.user)
  usuario.is_active = False
  usuario.save()
  logout(request)
  return redirect('cuenta:eliminar_confirmacion')


def registrar_cuenta(request):
  if request.method == 'POST':
    registro_form = RegistroForm(request.POST)
    
    if registro_form.is_valid():
      print('valido')
      usuario = registro_form.save(commit=False)
      usuario.email = registro_form.cleaned_data['email']
      usuario.set_password(registro_form.cleaned_data['password'])
      usuario.is_active = False
      usuario.save()
      
      current_site = get_current_site(request)
      asunto = 'Activa tu cuenta'
      mensaje = render_to_string('cuenta/registro/email_activacion_cuenta.html',{
        'usuario': usuario,
        'domain': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(usuario.pk)),
        'token': activar_token_cuenta.make_token(usuario),
      })
      usuario.email_usuario(asunto=asunto, mensaje=mensaje)

    else:
      print('invalido')
  
  else:
    registro_form = RegistroForm()
  
  return render(request, 'cuenta/registro/registrar.html', {'form': registro_form})


def activar_cuenta(request, uidb64, token):
  try:
    uid = force_str(urlsafe_base64_decode(uidb64))
    usuario = UsuarioBase.objetos.get(pk=uid)

  except Exception as e:
    print(e)
    usuario = None

  if usuario is not None and activar_token_cuenta.check_token(usuario, token):
    usuario.is_active = True
    usuario.save()
    login(request, usuario)
    return redirect('cuenta:control_panel')

  else:
    return render(request, 'cuenta/registro/activacion_invalida.html')

templates/cuenta/usuario/control_panel.html
{% extends "../../tienda/base.html" %} 
{% load static %} 
{% block titulo %} Tienda Online | Panel de control {%endblock %} 

{% block contenido %}

<main class="pt-5">

  <div class="container" style="max-width: 1000px">
    <div class="col-12">
      <h1 class="h2">Panel de control</h1>
    </div>
    <div class="col-12 d-flex justify-content-between">
      <div>Administra tus <b>ordenes</b> e información personal</div>
      <div><a href="{% url "cuenta:editar_detalles" %}">Cambiar información</a></div>
    </div>
    <hr />
  </div>

  <div class="container" style="max-width: 1000px">

  </div>

</main>

{% endblock %}

templates/cuenta/usuario/editar_detalles.html
{% extends "../../tienda/base.html" %}
{% block titulo %}Editar Perfil{% endblock %}
{% block contenido %}

<style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>

<div class="container-fluid">
  <div class="row no-gutter">
    <div class="col-md-12">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-12 col-lg-7 mx-auto">

              <form class="account-form px-4 pt-4" method="post" enctype="multipart/form-data">

                {% csrf_token %}

                {% if usuario_form.is_valid %}
                <div class="alert alert-primary" role="alert">
                  Información editada exitosamente
                </div>

                <p class="small text-center pt-0">
                  <a href="{% url "cuenta:control_panel" %}">Volver al Panel de Control</a>
                </p>

                {%else%}

                <h3>Cambiar información</h3>
                <p>Puedes cambiar tu información con el siguiente formulario:</p>

                {% endif %}

                {% if form.errors %}
                <div class="alert alert-primary" role="alert">
                    Error: Por favor intenta de nuevo!
                </div>
                {% endif %}

                <label class="small font-weight-bold">{{ usuario_form.email.label}}</label>
                {{ usuario_form.email }}

                <label class="small font-weight-bold">{{ usuario_form.nombre_usuario.label}}</label>
                {{ usuario_form.nombre_usuario }}

                <label class="small font-weight-bold">{{ usuario_form.nombre.label}}</label>
                {{ usuario_form.nombre }}

                <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit" value="Save changes">Guardar Cambios</button>

                <hr class="mb-3">
              </form>
              
              <form class="account-form px-4" action="{% url "cuenta:eliminar_usuario" %}" method="post">

                {% csrf_token %}
                <p class=" h3 pt-4 font-weight-bold">Eliminar Cuenta</p>
                <p>¿Estas seguro que quieres eliminar la cuenta?</p>
                <button type="submit" role="button" class="btn btn-danger btn-block py-2 mb-4 mt-5 fw-bold w-100">Eliminar</button>

              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/cuenta/usuario/eliminar_confirmacion.html
{% extends "../../tienda/base.html" %}
{% block titulo %}Eliminar Cuenta{% endblock %}
{% block contenido %}

<style>
  .account-form input {
    border: 2px solid #ccc;
    height: calc(2em + .75rem + 2px);
  }

.account-form input:focus {
  border-color: #1497ff;
  box-shadow: none;
  }
</style>

<div class="container-fluid">
  <div class="row no-gutter">
    <div class="col-md-12">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-12 col-lg-6 mx-auto">
              <div class="p-4">
                <h3 class="mb-4">Cuenta Eliminada</h3>
                <p>Vuelva Pronto, Gracias</p>
              </div>       
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/cuenta/usuario/reiniciar_estado.html
{% extends "../../tienda/base.html" %}
{% block titulo %}Reiniciar Contraseña Exitoso{% endblock %}
{% block contenido %}

<style>
  .container-fluid {
    max-width: 100%;
  }

  .account-form input {
    border: 2px solid #ccc;
    height: calc(2em + .75rem + 2px);
  }

  .account-form input:focus {
    border-color: #1497ff;
    box-shadow: none;
  }
</style>


<div class="container-fluid">
  <div class="row no-gutter">
    <div class="col-md-12">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-12 col-lg-6  mx-auto">
              <div class="p-4">

                {% if 'email' in request.get_full_path %}
                  <h3 class="mb-4">Reinicio de contraseña exitoso</h3>
                  <p>Revise su correo electrónico para obtener instrucciones</p>
                {% endif%}

                {% if 'completo' in request.get_full_path %}
                  <h3 class="mb-4">Reinicio de contraseña exitoso</h3>
                  <a href="{% url "cuenta:login" %}">Login</a>
                {% endif%}

              </div>       
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/cuenta/usuario/reiniciar_password.html
{% extends "../../tienda/base.html" %}
{% block titulo %}Reiniciar Contraseña{% endblock %}
{% block contenido %}

{% if request.user.is_authenticated %}
  <script>
    window.location.href = '{% url "cuenta:control_panel" %}';
  </script>
{% endif %}

<style>
  .account-form input {
    border: 2px solid #ccc;
    height: calc(2em + .75rem + 2px);
  }

  .account-form input:focus {
    border-color: #1497ff;
    box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
  }
</style>

<div class="container-fluid">
  <div class="row no-gutter">
    <div class="col-md-12">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-12 col-md-12 mx-auto">

              <form class="account-form p-4 rounded col-lg-8 mx-auto" method="post" action="{% url 'cuenta:reiniciar_password' %}">

                {% csrf_token %}
                <p class="h3 mb-4 font-weight-bold">¿Olvidaste tu contraseña?</p>
                <p>Ingresa tu E-mail para obtener una nueva.</p>
                {% if form.errors %}
                <div class="alert alert-primary" role="alert">
                  Error: Por favor intenta de nuevo
                </div>
                {% endif %}
                <label class="small font-weight-bold">{{ form.email.label}}</label>
                {{ form.email }}
                <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit"value="Send e-mail">Enviar</button>
                <p class="text-center"><a href="{% url "cuenta:login" %}">Login</a></p>

              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/cuenta/usuario/reiniciar_password_confirmacion.html
{% extends "../../tienda/base.html" %}
{% block titulo %} Reiniciar Contraseña {% endblock %}
{% block contenido %}

{% if request.user.is_authenticated %}
<script>
    window.location.href = '{% url "cuenta:control_panel" %}';
</script>
{% endif %}

<style>
  .login,
  .image {
    min-height: 100vh;
  }

  .bg-image {
    background-image: url('https://picsum.photos/id/433/1080');
    background-size: cover;
    background-position: center center;
  }

  .container-fluid {
    max-width: 100%;
  }

  body {
    margin-bottom: 0px;
  }
  .account-form input {
    border: 2px solid #ccc;
    height: calc(2em + .75rem + 2px);
  }

  .account-form input:focus {
      border-color: #1497ff;
      box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
  }
</style>


<div class="container-fluid">
  <div class="row no-gutter">
    <div class="col-md-6 bg-light">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-12 col-md-12 mx-auto">

              <form class="login-form p-4 rounded" method="post">
                {% csrf_token %}
                <h1 class="h4 mb-4 font-weight-bold">Change your password</h1>
                <p>Use the form below to change your password.</p>

                {% if form.errors %}
                <div class="alert alert-primary" role="alert">
                    Error: Please try again!
                </div>
                {% endif %}

                {% if form.errors %}
                  <p>Por favor corrige los siguientes errores:</p>

                  {% for field in form %}

                    {% if field.errors %}
                      <div class="alert alert-primary" role="alert">
                      {{ field.label }}: {{ field.errors|striptags }}
                      </div>
                    {% endif %}

                  {% endfor %}
                {% endif %}

                <label class="small font-weight-bold">{{ form.new_password1.label}}</label>
                {{ form.new_password1 }}
                <label class="small font-weight-bold">{{ form.new_password2.label}}</label>
                {{ form.new_password2 }}
                <ul>
                  <li>Your password can’t be too similar to your other personal information.</li>
                  <li>Your password must contain at least 8 characters.</li>
                  <li>Your password can’t be a commonly used password.</li>
                  <li>Your password can’t be entirely numeric.</li>
                </ul>
                <button class="btn btn-primary btn-block py-2 mb-4 mt-5 font-weight-bold" type="submit"
                    value="Change">Submit
                </button>
              </form>

              <p class="small text-center pt-4">
                <a href="{% url "cuenta:login" %}">Already have an account?</a>
              </p>

            </div>
          </div>
        </div>
      </div>
    </div>
    
    <div class="col-md-6 d-none d-md-flex bg-image"></div>
  </div>
</div>

{% endblock %}

templates/cuenta/usuario/reiniciar_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'cuenta:reiniciar_password_confirmacion' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}