carrito/urls.py
from django.urls import path
from . import views

app_name = 'carrito'

urlpatterns = [
    path('', views.carrito_resumen, name='carrito_resumen'),
    path('agregar/', views.carrito_agregar, name='carrito_agregar'),
    path('eliminar/', views.carrito_eliminar, name='carrito_eliminar'),
    path('actualizar/', views.carrito_actualizar, name='carrito_actualizar'),
]

cuenta/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .forms import (UsuarioLoginForm, PasswordReiniciarForm, PasswordReiniciarConfirmacionForm)
from . import views

app_name = 'cuenta'

urlpatterns = [
  path('login/', auth_views.LoginView.as_view(
    template_name='cuenta/registro/login.html', 
    form_class=UsuarioLoginForm), 
    name='login'),

  path('logout/', auth_views.LogoutView.as_view(
    next_page='/cuenta/login/'), 
    name='logout'),

  path('registrar/', views.registrar_cuenta, name='registrar'),

  path('activar/<slug:uidb64>/<slug:token>', views.activar_cuenta, name='activar'),

  path('reiniciar_password/', auth_views.PasswordResetView.as_view (
    template_name='cuenta/usuario/reiniciar_password.html', 
    success_url='reiniciar_password_confirmacion_email', #1
    email_template_name='cuenta/usuario/reiniciar_password_email.html',
    form_class=PasswordReiniciarForm),
    name='reiniciar_password'),
  #1
  path('reiniciar_password/reiniciar_password_confirmacion_email/', TemplateView.as_view(
    template_name="cuenta/usuario/reiniciar_estado.html"), 
    name='reiniciar_password_hecho'),

  path('reiniciar_password_confirmacion/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
  template_name='cuenta/usuario/reiniciar_password_confirmacion.html', 
  success_url='/cuenta/reiniciar_password_completo/', #2
  form_class=PasswordReiniciarConfirmacionForm),
  name="reiniciar_password_confirmacion"),
  #2
  path('reiniciar_password_completo/', TemplateView.as_view(template_name="cuenta/usuario/reiniciar_estado.html"), name='reiniciar_password_completo'),

  # Panel de control del usuario
  path('control_panel/', views.control_panel, name='control_panel'),

  path('perfil/editar/', views.editar_detalles, name='editar_detalles'),

  path('perfil/eliminar/', views.eliminar_usuario, name='eliminar_usuario'),

  path('perfil/eliminar_confirmacion/', TemplateView.as_view(
    template_name='cuenta/usuario/eliminar_confirmacion.html'), 
    name='eliminar_confirmacion'),
]

nucleo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls', namespace='tienda')),
    path('carrito/', include('carrito.urls', namespace='carrito')),
    path('cuenta/', include('cuenta.urls', namespace='cuenta')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path
from . import views

app_name = 'tienda' # Respetar nombre en ingles de la variable

urlpatterns = [
    path('', views.productos_all, name='productos_all'),
    path('item/<slug:slug>/', views.producto_detalles, name='producto_detalles'),
    path('categoria/<slug:categoria_slug>/', views.categoria_lista, name='categoria_lista'),
]

tienda/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class Categoria(models.Model):
  nombre = models.CharField(max_length=255, db_index=True)
  slug = models.SlugField(max_length=255, unique=True)

  class Meta:
    verbose_name_plural = 'Categorias'

  def get_absolute_url(self):
      return reverse('tienda:categoria_lista', args=[self.slug])

  def __str__(self):
    return self.nombre


class ProductoManager(models.Manager):
  def get_queryset(self):
    return super(ProductoManager, self).get_queryset().filter(activo=True)


class Producto(models.Model):
  categoria = models.ForeignKey(Categoria, related_name='producto', on_delete=models.CASCADE)
  creado_por = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='producto_creador')
  titulo = models.CharField(max_length=255)
  autor = models.CharField(max_length=255, default='admin')
  descripcion = models.TextField(blank=True)
  imagen = models.ImageField(upload_to='images/', default='images/default.png')
  slug = models.SlugField(max_length=255)
  precio = models.DecimalField(max_digits=4, decimal_places=2)
  en_stock = models.BooleanField(default=True)
  activo = models.BooleanField(default=True)
  creado = models.DateTimeField(auto_now_add=True)
  actualizado = models.DateTimeField(auto_now=True)
  # objects = ProductoManager()
  objects = models.Manager()
  producto = ProductoManager()

  class Meta:
    verbose_name_plural = 'Productos'
    ordering = ('-creado',)

  def get_absolute_url(self):
      return reverse('tienda:producto_detalles', args=[self.slug])
  
  def __str__(self):
    return self.titulo

tienda/views.py
from django.shortcuts import render, get_object_or_404
from .models import Categoria, Producto


def productos_all(request):
  productos = Producto.producto.all() # Toma todos los productos de la base de datos
  return render(request, 'tienda/home.html', {'productos': productos})

def producto_detalles(request, slug):
  producto = get_object_or_404(Producto, slug=slug, en_stock=True)
  return render(request, 'tienda/productos/producto.html', {'producto': producto})

def categoria_lista(request, categoria_slug):
  categoria = get_object_or_404(Categoria, slug=categoria_slug)
  productos = Producto.objects.filter(categoria=categoria)
  return render(request, 'tienda/productos/categoria.html', {'categoria': categoria, 'productos': productos})

templates/tienda/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">

  <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>

  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js
  "></script>

  <link rel="stylesheet" href="{% static 'carrito/css/carrito.css' %}">

  <title> {% block titulo %} Mi tienda {% endblock %} </title>

</head>

<body>
  <div class="container py-3">

    <nav class="navbar navbar-expand-md bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Tienda</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categorias
              </a>
              <ul class="dropdown-menu">

                {% for c in categorias %}
                  <li><a class="dropdown-item" href="{{ c.get_absolute_url }}">{{c.nombre}}</a></li>
                {% endfor %}

                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Ver todas</a></li>
              </ul>
            </li>
          </ul>

          {% if user.is_authenticated %}
          <a type="button" role="button" href="{% url 'cuenta:logout' %}" class="btn btn-outline-secondary border-0 basket-btn">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-door-closed" viewBox="0 0 16 16">
                <path d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
              </svg>
            </div>
            <span class="fs15 fw500">Salir</span>
          </a>

          {% else %}

          <a type="button" role="button" href="{% url 'cuenta:login' %}" class="btn btn-outline-secondary border-0 basket-btn">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-door-closed" viewBox="0 0 16 16">
                <path d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
              </svg>
            </div>
            <span class="fs15 fw500">Entrar</span>
          </a>
          {% endif %}


          <a type="button" role="button" href="{% url 'cuenta:control_panel' %}"
              class="btn btn-outline-secondary border-0 basket-btn">
              <div>
                  <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                      class="bi bi-person" viewBox="0 0 16 16">
                      <path
                          d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                  </svg>
              </div>
              <span class="fs15 fw500">Cuenta</span>
          </a>


          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Buscar</button>
          </form>

          <a class="ms-2 btn btn-outline-secondary carrito-btn" type="button" role="button" href="{% url 'carrito:carrito_resumen' %}">

            {% with cantidad_total=carrito|length %}
              <div id="carrito-cantidad" class="d-inline-flex carrito-cantidad">
                {% if cantidad_total > 0 %}
                  {{ cantidad_total }}
                {% else %}
                  0
                {% endif %}
              </div>
            {% endwith %}

            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
              <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </svg>

            <div class="fs15 fw500">Carrito</div>
            
          </a>

        </div>
      </div>
    </nav>    
    <hr class="hr">

    <div id="content"> {% block contenido %} {% endblock %}</div>

    <footer class="container py-5 footer">
      <hr>
      <div class="row pt-4">
        <div class="col-12 col-md">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-asterisk" viewBox="0 0 16 16">
              <path d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z" />
          </svg>
          <small class="d-block mb-3 text-muted">&copy; 2017-2021</small>
        </div>
        <div class="col-6 col-md fs15">
          <h5>Features</h5>
          <ul class="list-unstyled">
            <li><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
          </ul>
        </div>
        <div class="col-6 col-md fs15">
          <h5>Resources</h5>
          <ul class="list-unstyled">
            <li><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
          </ul>
        </div>
        <div class="col-6 col-md fs15">
          <h5>Resources</h5>
          <ul class="list-unstyled">
            <li><a class="link-secondary text-decoration-none" href="#">Business</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Education</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Government</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Gaming</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>About</h5>
          <ul class="list-unstyled">
            <li><a class="link-secondary text-decoration-none" href="#">Team</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
            <li><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
          </ul>
        </div>
      </div>
  </footer>


  </div>
</body>

</html>

templates/tienda/home.html
{% extends "./base.html" %}
{% load static %}
{% block titulo %} Tienda Online {% endblock %}

{% block contenido %}
  
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {% for p in productos %}

        <div class="col">
          <div class="card shadow-sm">
            
            <!-- <img src="{{ p.imagen.url }}" class="card-img-top" alt="..."> -->
            <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ p.imagen.url }}">

            <div class="card-body">
              <p class="card-text">{{ p.titulo|title }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <a class="btn-group" href="{{ p.get_absolute_url }}">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Ver</button>
                </a>
                <small class="text-muted"> ${{ p.precio }}</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}
        
      </div>
    </div>
  </div>

{% endblock %}